### ISSUE TITLE
[Bug] <Error in session - 1 task page>

### ISSUE THREAD

**Issue by zawrabh** [campusx-official/dsmp-2022-23#3]
session - 1 task page is generating an error to load the ipynb task file.

![image](https://user-images.githubusercontent.com/95751390/200723496-bb339a08-f8c7-4fb2-8b98-3e93f8db2784.png)

@campusx-official

**Comment by campusx-official** [comment]
Here is the link - https://colab.research.google.com/drive/1j7D_owmjwodnY8zedxdpIOQIyB-GufeU?usp=sharing

**Comment by zawrabh** [comment]
thank you for the link sir and please update it on the page also so that others would not have to face this issue.
